change hash algorithm compatible for fetchNextcloudApp
helsinki-systems/nc4nix pull request #3
Opened 2022-12-08 08:48 UTC by onny

2023-06-01 11:09 UTC, Scriptkiddi commented
Hey isnt there a better way to calculate that hash instead of spawing seperate processes? And why is this a good idea?

2023-06-02 08:49 UTC, onny commented
@Scriptkiddi I guess calculating hashes has changed since https://github.com/NixOS/nixpkgs/pull/193075 and nc4nix probably didn't got updated yet.
Yeah it would be cool to calculate it with Go but not sure how to do it

2023-06-02 09:13 UTC, Scriptkiddi commented
I think we should rework this to go code and then merge it

2024-02-05 12:44 UTC, onny commented
> I think we should rework this to go code and then merge it

Found a way to calculate the hash in Go without depending on external commands :)

2024-02-06 14:52 UTC, onny commented
@Scriptkiddi @dasJ

2024-02-06 19:32 UTC, leonklingele requested changes

2024-02-06 19:32 UTC, leonklingele commented on main.go
> +		log.Fatal(err)
Don't log the error and instead return it:

```suggestion
		return "", fmt.Errorf("failed to create temp dir: %w", err)
```

2024-02-06 19:32 UTC, leonklingele commented on main.go
> +	err = nar.DumpPath(h, entryPath)
Combine this declaration with the next line:

```go
if err := nar.DumpPath(h, entryPath); err != nil {
```

2024-02-06 19:32 UTC, leonklingele commented on main.go
> +		panic(err)
Don't panic, instead return the error:

```suggestion
		return "", fmt.Errorf("failed to dump path: %w", err) 
```

2024-02-06 19:32 UTC, leonklingele commented on main.go
> +	sha256 = nixbase32.EncodeToString(h.Sum(nil))
Why not remove the `var sha256 string` above and make this a

```suggestion
	return nixbase32.EncodeToString(h.Sum(nil)), nil
```

2024-02-08 12:23 UTC, onny commented
Thank you @leonklingele , fixed the issues 👍

2024-02-09 16:35 UTC, leonklingele commented on main.go
> +	var sha256 string
```suggestion
```

2024-02-09 17:15 UTC, onny commented
Oh missed that, thank you!

2024-02-09 17:24 UTC, leonklingele approved these changes

2024-02-12 11:05 UTC, onny commented
@ajs124

2024-02-15 13:21 UTC, onny commented
Is there anything I can test or further add please let me know :)

2024-02-19 20:58 UTC, leonklingele commented
@onny thanks! Code-wise this lgtm, what's the intention behind this change though? Does the current version (i.e. latest `master`) yields any different (incorrect?) hashes?

2024-02-19 21:42 UTC, onny commented
yes the hash is now different, probably because fetchnextcloudapp requires a recursive hash, not of the single zip file line before, but of the zip content recursively https://github.com/NixOS/nixpkgs/blob/c5e62ec76a0198822c1cf017f83c1d4c9d1ceb60/pkgs/servers/nextcloud/packages/default.nix#L18

2024-02-19 21:57 UTC, leonklingele commented
To me this change looks like it's switching to the new hash _representation_ used by nix which additionally allows for different hashing algorithms (e.g. `sha1`, .. instead of `sha256`). i.e., it's not _changing_ the hash, it's merely using a _different encoding_ of it.

@Conni2461 @dasJ what do you think? nc4nix is more performant when not using this change, and instead leaving the hash-calculation to stdlib's `sha256.Sum256`.

2024-02-19 23:55 UTC, onny commented
> To me this change looks like it's switching to the new hash _representation_ used by nix which additionally allows for different hashing algorithms (e.g. `sha1`, .. instead of `sha256`). i.e., it's not _changing_ the hash, it's merely using a _different encoding_ of it.
> 
> @Conni2461 @dasJ what do you think? nc4nix is more performant when not using this change, and instead leaving the hash-calculation to stdlib's `sha256.Sum256`.

sha256.Sum256 only hashes the zip file whereas this PR calculates the hash by unpacking the zip and calculating the hash recursively over all containing files, see:
```
$ nix-prefetch-url --unpack "https://github.com/nextcloud/bookmarks/releases/download/v13.1.3/bookmarks-13.1.3.tar.gz"
06pprhlaaqdha2nmfdcf76mhh48hdr5jlv88snxji8lpflv50wr5
$ nix-prefetch-url  "https://github.com/nextcloud/bookmarks/releases/download/v13.1.3/bookmarks-13.1.3.tar.gz"
0yl1agr62y87bil321ryrl0qwp9m0gksgwhvcqqlkxgwnjs98d7n
```

the unpacked hash is used in fetchNextcloudApp because this function also uses fetchzip with recursive hash calculation: https://github.com/NixOS/nixpkgs/blob/791355b27c5bfc58f7339a3dafc936ec50130e01/pkgs/build-support/fetchnextcloudapp/default.nix

2024-02-20 00:04 UTC, leonklingele commented
> sha256.Sum256 only hashes the zip file whereas this PR calculates the hash by unpacking the zip and calculating the hash recursively over all containing files

I'm not 100% fluent in Nix but I can't see a difference here from a integrity-preserving point of view. Let's see what my work mates have to say. I'll get back to you tomorrow! :)

2024-02-20 00:13 UTC, leonklingele requested changes
Sorry, this slipped!

2024-02-20 00:13 UTC, leonklingele commented on main.go
> +	}
Just noticed that this directory should be removed after use here, and not further down below, i.e.

```suggestion
	dname, err := os.MkdirTemp("", "")
	if err != nil {
		return "", fmt.Errorf("failed to create temp dir: %w", err)
	}
	defer func() {
		if err := os.RemoveAll(dname); err != nil {
			log.Printf("failed to clean up temp dir %q: %v", dname, err)
		}
	}()
```

2024-02-20 00:13 UTC, leonklingele commented on main.go
> +	defer os.RemoveAll(dname)
```suggestion
```

2024-02-20 17:40 UTC, leonklingele commented
My work mates are busy this week, unfortunately. We‘ll get back to you asap!

2024-03-01 09:28 UTC, cheriimoya commented
I checked the output and somehow, there are some empty values. If I run `rg '"sha256": ""' *.json` but I just noticed, it also happens with the current implementation. Maybe those should be handled/debugged in a separate Issue.

Otherwise, the PR looks good to me and can be merged.

2024-03-01 09:28 UTC, merged

2024-03-01 10:41 UTC, onny commented
thank you so much for helping and merging this :)

2024-04-23 19:40 UTC, leonklingele commented
Hey @onny :) Just fyi: We have updated this again with https://github.com/helsinki-systems/nc4nix/commit/3c35a0efda57bb633a137463f46266ba3b04d3c0 — we now no longer extract the zip archive due to bug with some of the Nextcloud apps which yielded an incorrect hash. We however still use an SRI hash.

2024-08-01 11:31 UTC, dotlambda commented
> We have updated this again with [3c35a0e](https://github.com/helsinki-systems/nc4nix/commit/3c35a0efda57bb633a137463f46266ba3b04d3c0) — we now no longer extract the zip archive due to bug with some of the Nextcloud apps which yielded an incorrect hash.

Does that not create problems regarding reproducability as outlined in https://github.com/NixOS/nixpkgs/pull/193075?
cc @Ma27